### ISSUE TITLE
安定版md_enを作る

### ISSUE THREAD

**Issue by harukahotta** [MIROC-DOC/model_description#30]
md_enに残っている間違い(#21,#26,放射過程の数式)を修正し、安定版としてリリースする。８月中に終わらせる予定。
これをリリース後は、2000年verのドキュメントを修正したくなったらmd_enだけ修正する（tex_jpx等を修正する必要はない）
ことで対処しようと考えています。

**Comment by kanonundgigue** [comment]
#27 の作業にあたって本文(md_en)を修正する必要があるので、（多分大丈夫だけど）conflictしないようにみつつやりましょう。

**Comment by harukahotta** [comment]
#34 #35で完了。
