### ISSUE TITLE
parse_jp.pyが動かない

### ISSUE THREAD

**Issue by harukahotta** [MIROC-DOC/model_description#31]
`./parse_jp.py -f -S -R -D -M -Td -Ev -d tex_jpx tex_jp/agcm.tex`
を実行すると
```
Panic in dennou [(2, 'No such file or directory')]
Traceback (most recent call last):
  File "/Users/harukahotta/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pyparsing.py", line 2572, in parseFile
    file_contents = file_or_filename.read()
AttributeError: 'str' object has no attribute 'read'
```

のエラーが出る。
[このコミット](https://github.com/MIROC-DOC/model_description/pull/21/commits/8faf10f485985c24f425789729e9dffeef43e3d6)
で変更された、org/tex_jp/agcm.texファイルのinclude指定では、parse_jp.pyが機能していないためと考えられる。

**Comment by saitofuyuki** [comment]
Fixed.
