### ISSUE TITLE
ディレクトリ整理

### ISSUE THREAD

**Issue by harukahotta** [MIROC-DOC/model_description#32]
現状の[model_description/md_en](https://github.com/MIROC-DOC/model_description/tree/master/md_en)を[model_description/org](https://github.com/MIROC-DOC/model_description/tree/master/org)以下に移動。今もリンクは貼られてますが。
新規ドキュメント作成場[model_description/md_en](https://github.com/MIROC-DOC/model_description/tree/master/md_en)をdraftみたいな名前にしたい。

理由１：既存のmd_enと、新規のmd_enを独立に更新できるよう、置く場所を別にしたい。
理由２：新規ドキュメントはmdともenとも限らない

作業は一瞬だが、conflictが生じるのでタイミングに気をつけてやる。9/1の打ち合わせ前にできるとよい。

ご意見あればぜひお願いします。

**Comment by harukahotta** [comment]
#38で完了。

**Comment by kanonundgigue** [comment]
[./org/md_en](https://github.com/MIROC-DOC/model_description/tree/master/org/md_en)を残しておくメリットは？[./draft](https://github.com/MIROC-DOC/model_description/tree/master/draft)と両方に同じファイルがあったら、今後の更新で戸惑いそう。安定版md_enということなら、そのバージョンでリリースorパッケージとしてpublishするのはどうでしょうか。

**Comment by harukahotta** [comment]
2000verのmd_enを更新可能な状態で残して置くのは価値があると思っている。
混乱を避けるために、むしろdraft/以下のファイルを削除するのがよいかと。
publish(安定版ブランチ？)を作るのもありか。
